backend:
  name: git-gateway
  branch: 8-seprate-current-and-former-people # Branch to update (optional; defaults to master)
  media_folder: "static/images/uploads"

local_backend: true

# publish_mode: editorial_workflow

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: deanlab
    api_key: 946847634736656

collections:
  - name: "equipment"
    label: "Equipment"
    folder: "content/equipment"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Position"
        name: "position"
        widget: "string"
      - lable: "Current or Former"
        name: "status"
        widget: "select"
        options: ["current", "former"]
      - label: "About"
        name: "about"
        widget: "string"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "research"
    label: "Research"
    folder: "content/research"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "date"
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "content/publications.md"
        label: "Publications"
        name: "publications"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
